### ISSUE TITLE
No requirements file

### ISSUE THREAD

**Issue by andy-io** [ratancs/learning-django-web-development#1]
Hi, there is no requirements file. How to install all the dependencies ? I tried to sort them out myself. But still i get an error respective to tastypie integration:

the traceback is:
/resources.py", line 2210, in BaseModelResource
    @transaction.commit_on_success()
AttributeError: 'module' object has no attribute 'commit_on_success'

Could you please update the repo with a clear requirements file and also a working project without bugs?

Thanks.

**Comment by eloyvega** [comment]
Please do

**Comment by ratancs** [comment]
sorry for responding late have added the requirements.txt file generated from the project.

used command  

pip freeze > requirements.txt
- I have mentioned in the book to generate this file. but to close this issue I have generated and attached.
