### ISSUE TITLE
project code different from book

### ISSUE THREAD

**Issue by andy-io** [ratancs/learning-django-web-development#2]
Hi, 

I see that the project code in github is different from what is shown in the book. For example in the ajax chapter, you are talking about bookmark.html file in templates directory but this is not in the repo. The chapter is totally not followable with the code you have written in the book and it is not working as well.

**Comment by rvzzz** [comment]
The presentation flow of the book's content in some chapters sounds confusing. 
Are you planing to release a new edition of the book? - with great revision and also with the newest version of the framework? - that would be awesome.
Also, if you could provide a `requirements.txt` file in the repo, that would be great and very appreciated.

**Comment by andy-io** [comment]
@rvnerd Looks like poor support from the authors. Clearly this is no book meeting professional standard.

**Comment by donMichaelL** [comment]
Hello, i am reading the book and its kind confusing in chapter 6.  As @andy-io commented, bookmark model is not defined, i think by bookmark the author means hashtags. And in chapter 6 for no reason in views.py the author follows the function-based view method.

**Comment by ratancs** [comment]
requirements.txt has been added.

there have been some editing mistakes in chapter 6. there are no such things as Bookmark class in this book.  I will update here about the updated chapter 6.

**Comment by VanWade** [comment]
Hi, @ratancs .I read your book recently.Everything goes well until chapter 6 .There are some confusing contents there.Have you updated it by now?
