### ISSUE TITLE
your TweetForm code does not work

### ISSUE THREAD

**Issue by realbezp** [ratancs/learning-django-web-development#3]
Hi, your code on chapter 4 for "class PostTweet(View)" does not seem to work.

I think something with the logic is wrong with your code. (maybe i am wrong because i am a newbie).
First of all, when we request "user/username/" there isn't any code to render our TweetForm, because there is no code related to TweetForm in our "Profile(view)" and 

the TweetForm is created by PostTweet(View) but it is not called until we click the post button and request "user/username/post/" url. 

Isn't something wrong with this logic?

**Comment by david-oh-git** [comment]
almost every piece of code in this book is wrong so far
